# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [9]:
import numpy as np

In [12]:
n = 10
my_array = np.arange(n)
my_array = my_array[::-1] 

In [13]:
my_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [18]:
my_diag = np.diag(my_array, k=0)
my_diag

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
np.trace(my_diag)

45

# Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [20]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [21]:
b = np.array( [4, 12, -3] )

In [22]:
from numpy import linalg

In [23]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [24]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True